import type { StreamingContent } from '../types/content';

export const mockContent: StreamingContent[] = [
  {
    id: 1,
    title: 'Neon Horizon',
    description: 'In 2087, a rogue AI architect awakens inside the neural grid of a fractured megacity and must navigate corporate espionage, synthetic memories, and her own erased past to prevent a city-wide consciousness collapse.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-neon/400/225',
    video_url: null,
    genre: 'Sci-Fi',
    content_type: 'movie',
    release_year: 2024,
    rating: 8.4,
    created_at: '2024-01-10T00:00:00.000Z',
    updated_at: '2024-01-10T00:00:00.000Z',
  },
  {
    id: 2,
    title: 'The Long Descent',
    description: 'An acclaimed mountaineer discovers a hermit camp deep in the Himalayas. What begins as a survival story slowly unravels into an unsettling meditation on obsession and identity.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-descent/400/225',
    video_url: null,
    genre: 'Thriller',
    content_type: 'movie',
    release_year: 2023,
    rating: 7.9,
    created_at: '2024-01-11T00:00:00.000Z',
    updated_at: '2024-01-11T00:00:00.000Z',
  },
  {
    id: 3,
    title: 'Echo Chamber',
    description: 'A jazz musician in 1960s Havana finds herself caught between rival intelligence agencies, each promising her freedom — but only one is telling the truth.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-echo/400/225',
    video_url: null,
    genre: 'Drama',
    content_type: 'movie',
    release_year: 2024,
    rating: 8.1,
    created_at: '2024-01-12T00:00:00.000Z',
    updated_at: '2024-01-12T00:00:00.000Z',
  },
  {
    id: 4,
    title: 'Orbital',
    description: 'Six astronauts en route to Europa receive a distress signal from the abandoned station ahead. What they find there will redefine what it means to be alone.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-orbital/400/225',
    video_url: null,
    genre: 'Sci-Fi',
    content_type: 'movie',
    release_year: 2025,
    rating: 8.7,
    created_at: '2024-01-13T00:00:00.000Z',
    updated_at: '2024-01-13T00:00:00.000Z',
  },
  {
    id: 5,
    title: 'Paper Cuts',
    description: 'A true-crime journalist investigating a cold case begins to suspect the story was deliberately buried — and that someone very powerful wants it to stay that way.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-paper/400/225',
    video_url: null,
    genre: 'Thriller',
    content_type: 'movie',
    release_year: 2023,
    rating: 7.6,
    created_at: '2024-01-14T00:00:00.000Z',
    updated_at: '2024-01-14T00:00:00.000Z',
  },
  {
    id: 6,
    title: 'Pale Frequency',
    description: 'A brilliant but reclusive sound designer stumbles onto a frequency embedded in old vinyl records that appears to alter human memory. Season 1 of the acclaimed limited series.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-pale/400/225',
    video_url: null,
    genre: 'Sci-Fi',
    content_type: 'series',
    release_year: 2024,
    rating: 8.9,
    created_at: '2024-01-15T00:00:00.000Z',
    updated_at: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 7,
    title: 'The Cartographer',
    description: 'Set in a near-future where national borders are auctioned to corporations, a disgraced cartographer is forced to redraw a disputed territory — and rewrite history in the process.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-carto/400/225',
    video_url: null,
    genre: 'Drama',
    content_type: 'series',
    release_year: 2023,
    rating: 8.3,
    created_at: '2024-01-16T00:00:00.000Z',
    updated_at: '2024-01-16T00:00:00.000Z',
  },
  {
    id: 8,
    title: 'Cold Archive',
    description: 'Every 10 years, a small Arctic research team digs up a time capsule left by its predecessor. Season 3 uncovers something the previous teams were instructed to forget.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-cold/400/225',
    video_url: null,
    genre: 'Mystery',
    content_type: 'series',
    release_year: 2025,
    rating: 9.1,
    created_at: '2024-01-17T00:00:00.000Z',
    updated_at: '2024-01-17T00:00:00.000Z',
  },
  {
    id: 9,
    title: 'Between Floors',
    description: 'Four strangers trapped in a malfunctioning elevator for 11 hours. Each episode is one hour of real time. Nowhere to hide, no signal, no easy answers.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-floors/400/225',
    video_url: null,
    genre: 'Drama',
    content_type: 'series',
    release_year: 2024,
    rating: 7.8,
    created_at: '2024-01-18T00:00:00.000Z',
    updated_at: '2024-01-18T00:00:00.000Z',
  },
  {
    id: 10,
    title: 'Underscore',
    description: 'A raw, unflinching docuseries following five independent musicians across three continents as they try to record their debut albums with no label backing and no safety net.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-under/400/225',
    video_url: null,
    genre: 'Documentary',
    content_type: 'series',
    release_year: 2024,
    rating: 8.0,
    created_at: '2024-01-19T00:00:00.000Z',
    updated_at: '2024-01-19T00:00:00.000Z',
  },
  {
    id: 11,
    title: 'ZenithFlix Originals — Live Premiere',
    description: 'Watch the world premiere of "Cold Archive" Season 4 live with the cast, followed by a 45-minute Q&A with the showrunner.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-live1/400/225',
    video_url: null,
    genre: 'Event',
    content_type: 'live',
    release_year: 2025,
    rating: 9.0,
    created_at: '2024-01-20T00:00:00.000Z',
    updated_at: '2024-01-20T00:00:00.000Z',
  },
  {
    id: 12,
    title: 'Deep Focus: Filmmaker Masterclass',
    description: 'A live, unscripted deep-dive session with three of the most talked-about directors of the past decade. Audience questions welcome.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-focus/400/225',
    video_url: null,
    genre: 'Event',
    content_type: 'live',
    release_year: 2025,
    rating: 8.5,
    created_at: '2024-01-21T00:00:00.000Z',
    updated_at: '2024-01-21T00:00:00.000Z',
  },
  {
    id: 13,
    title: 'Last Light',
    description: 'A lighthouse keeper on a remote Norwegian island begins receiving transmissions that predate radio technology. A quiet, measured horror that rewards patience.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-light/400/225',
    video_url: null,
    genre: 'Horror',
    content_type: 'movie',
    release_year: 2024,
    rating: 7.7,
    created_at: '2024-01-22T00:00:00.000Z',
    updated_at: '2024-01-22T00:00:00.000Z',
  },
  {
    id: 14,
    title: 'The Parallel',
    description: 'A physicist discovers that her recently deceased sister is still alive — in an adjacent timeline. A sci-fi drama about grief, choice, and the weight of the road not taken.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-parallel/400/225',
    video_url: null,
    genre: 'Sci-Fi',
    content_type: 'series',
    release_year: 2025,
    rating: 8.6,
    created_at: '2024-01-23T00:00:00.000Z',
    updated_at: '2024-01-23T00:00:00.000Z',
  },
  {
    id: 15,
    title: 'Salt & Iron',
    description: 'Two rival fishing families on the coast of Iceland are forced into an alliance when a foreign trawler operation begins systematically destroying their shared waters.',
    thumbnail_url: 'https://picsum.photos/seed/zenith-salt/400/225',
    video_url: null,
    genre: 'Drama',
    content_type: 'movie',
    release_year: 2023,
    rating: 7.5,
    created_at: '2024-01-24T00:00:00.000Z',
    updated_at: '2024-01-24T00:00:00.000Z',
  },
];
